#!/bin/sh

toolchain="/home/andrey/kernel_build/android-toolchain-eabi-4.9/bin/arm-linux-androideabi-";
kernel_source_path="~/kernel_build/android_kernel_allview_p5_quad";

#$toolchain="~/android-toolchain-eabi-4.9/bin/arm-linux-androideabi-";
#$kernel_source_path="~/android/kernel_test/";

export CROSS_COMPILE=$toolchain
export TARGET_PRODUCT=simcom89_wet_jb2 MTK_ROOT_CUSTOM=../mediatek/custom
export TARGET_BUILD_VARIANT=user

cd kernel;
make -j6

